### ISSUE TITLE
Why groupId is needed ?

### ISSUE THREAD

**Issue by ThePredators** [LaserPhaser/gitlab-group-clone#6]
Hy, 

I got this error because i dont have any groupId : 

gitlab-clone: error: argument --group_id:

Thanks.

**Comment by LaserPhaser** [comment]
@ThePredators What do you want to clone? 
If you want to clone 1 repository just use "git clone"

This tool is for cloning groups of repositories

**Comment by ThePredators** [comment]
@LaserPhaser : no kidding, git clone (What a joke !)

I wasted my time here ! 

For serious people i advice you to use this tool instead ! --> https://github.com/gabrie30/ghorg
